# -*- coding: utf-8 -*-
SURF_TOP = "SURF_TOP"
SURF_RIB_BOTTOM = "SURF_RIB_BOTTOM"
SET_FIX_PADS = "SET_FIX_PADS"
SURF_FIX_PADS= "SURF_FIX_PADS"
PART_TRAY = "Tray"
INST_TRAY = "Tray-1"
# --- Platen (Rigid) ---
PART_PLATEN = "P_PLATEN"
INST_PLATEN = "I_PLATEN"
SURF_PLATEN = "SURF_PLATEN"
SET_RP_PLATEN = "SET_RP_PLATEN"
RB_PLATEN = "RB_PLATEN"